import os
import uuid
import time
import logging
from typing import Optional
from .schemas import SandboxExecutionRequest, SandboxExecutionResult
from datetime import datetime, timezone

logger = logging.getLogger(__name__)

class E2BManager:
    """Interface for managing E2B AI Sandbox sessions."""
    
    async def execute(self, request: SandboxExecutionRequest) -> SandboxExecutionResult:
        raise NotImplementedError

class RealE2BManager(E2BManager):
    """Implementation using the official E2B Code Interpreter SDK."""
    
    def __init__(self, api_key: str):
        self.api_key = api_key
        try:
            from e2b_code_interpreter import Sandbox
            self.Sandbox = Sandbox
        except ImportError:
            logger.warning("e2b_code_interpreter not installed. RealE2BManager will fail.")
            self.Sandbox = None

    async def execute(self, request: SandboxExecutionRequest) -> SandboxExecutionResult:
        if not self.Sandbox:
            return SandboxExecutionResult(
                execution_id=str(uuid.uuid4()),
                status="error",
                stdout="",
                stderr="E2B SDK not installed.",
                execution_time_ms=0,
                error_message="Missing dependency: e2b_code_interpreter"
            )
            
        start_time = time.time()
        try:
            # Note: E2B provides synchronous APIs mostly, using run_in_executor in production
            sandbox = self.Sandbox(api_key=self.api_key)
            
            # Install dependencies
            if request.dependencies:
                deps = " ".join(request.dependencies)
                if request.language == "python":
                    sandbox.commands.run(f"pip install {deps}")
                elif request.language in ("javascript", "typescript", "js", "ts"):
                    sandbox.commands.run(f"npm install {deps}")

            # Execute code
            execution = sandbox.run_code(
                request.code, 
                language=request.language,
                timeout=request.timeout_seconds
            )
            
            end_time = time.time()
            sandbox.close()

            return SandboxExecutionResult(
                execution_id=str(uuid.uuid4()),
                status="success" if not execution.error else "error",
                stdout="".join(m.line for m in execution.logs.stdout),
                stderr="".join(m.line for m in execution.logs.stderr),
                execution_time_ms=int((end_time - start_time) * 1000),
                error_message=execution.error.message if execution.error else None
            )
        except Exception as e:
            end_time = time.time()
            return SandboxExecutionResult(
                execution_id=str(uuid.uuid4()),
                status="error",
                stdout="",
                stderr=str(e),
                execution_time_ms=int((end_time - start_time) * 1000),
                error_message=str(e)
            )

class SimulatedE2BManager(E2BManager):
    """Simulated E2B manager for local development and testing without API keys."""
    
    async def execute(self, request: SandboxExecutionRequest) -> SandboxExecutionResult:
        start_time = time.time()
        # Simulate network delay for starting sandbox
        time.sleep(1.2)
        
        stdout = ""
        stderr = ""
        status = "success"
        error_msg = None
        
        # Simulate dependency installation
        if request.dependencies:
            stdout += f"Installing dependencies: {', '.join(request.dependencies)}...\n"
            time.sleep(0.5)
            stdout += "Successfully installed packages.\n\n"
        
        # Simulate execution logic based on code content
        code = request.code.lower()
        if "error" in code or "raise" in code or "throw" in code:
            status = "error"
            stderr = "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nRuntimeError: Simulated execution error"
            error_msg = "Simulated runtime error"
        elif "while true" in code or "time.sleep(100)" in code:
            status = "timeout"
            stderr = f"Execution timed out after {request.timeout_seconds} seconds."
            error_msg = "Timeout exceeded"
            time.sleep(min(3, request.timeout_seconds))
        else:
            # Simulate generic successful execution
            stdout += f"Execution started (language: {request.language})\n"
            time.sleep(0.8)
            stdout += f"Output generated by AI Agent sandbox.\n"
            if "print" in code or "console.log" in code:
                stdout += "Hello from isolated sandbox!\n"
        
        end_time = time.time()
        
        return SandboxExecutionResult(
            execution_id=str(uuid.uuid4()),
            status=status,
            stdout=stdout,
            stderr=stderr,
            execution_time_ms=int((end_time - start_time) * 1000),
            error_message=error_msg,
            timestamp=datetime.now(timezone.utc)
        )

def get_e2b_manager(mode: str = "simulated", api_key: Optional[str] = None) -> E2BManager:
    """Factory function to get the appropriate E2B Manager."""
    if mode == "live" and api_key:
        return RealE2BManager(api_key)
    return SimulatedE2BManager()
