import uuid
import time
import hashlib
import logging
from .schemas import SanitizationRequest, SanitizationResponse

logger = logging.getLogger(__name__)

class DangerzoneManager:
    """Interface for managing Document Sanitization (Dangerzone)."""
    async def sanitize_document(self, file_content: bytes, request: SanitizationRequest) -> SanitizationResponse:
        raise NotImplementedError

class SimulatedDangerzoneManager(DangerzoneManager):
    """Simulated Dangerzone Manager for local testing."""
    async def sanitize_document(self, file_content: bytes, request: SanitizationRequest) -> SanitizationResponse:
        task_id = str(uuid.uuid4())
        orig_sha256 = hashlib.sha256(file_content).hexdigest()
        
        # Simulate processing time (Dangerzone is notoriously slow because it spins up 2 containers per doc)
        # We will sleep a short amount for simulation purposes
        time.sleep(1.0)
        
        # In a real implementation, we would pass the file_content to the Dangerzone pipeline,
        # which pixelates it and returns a new PDF. 
        # Here we just generate a mock safe PDF byte content.
        mock_safe_pdf = b"%PDF-1.4\n%Mock Safe Document generated by Simulated Dangerzone\n%%EOF"
        safe_sha256 = hashlib.sha256(mock_safe_pdf).hexdigest()
        
        return SanitizationResponse(
            task_id=task_id,
            status="safe",
            safe_file_url=f"/api/v1/isolation/download/{task_id}", # mock URL
            original_sha256=orig_sha256,
            safe_sha256=safe_sha256,
            message="Document successfully sanitized."
        )

def get_dangerzone_manager(mode: str = "simulated") -> DangerzoneManager:
    """Factory function to get the appropriate Dangerzone Manager."""
    return SimulatedDangerzoneManager()
