apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-deployment.yaml
  - postgres-statefulset.yaml
  - redis-deployment.yaml
  - worker-daemonset.yaml
  - network-policy.yaml
  - postgres-backup-cronjob.yaml
